sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gtseamus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gtseamus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-128720173870"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  
